[tool.poetry]
name = "dominions-bot"
version = "0.0.0"
description = "Bot for keeping track of dominions turns for slack and discord"
authors = ["stvnksslr <stvnksslr@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
discord = "^1.0.1"
requests = "^2.22.0"
python-dotenv = "^0.10.3"
sqlalchemy = "^1.3.10"
pendulum = "^2.0.5"
alembic = "^1.2.1"
schedule = "^0.6.0"
psycopg2-binary = "^2.8.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2.1"
pytest-cov = "^2.8.1"
pytest-sugar = "^0.9.2"
flake8 = "^3.7.8"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
